### ISSUE TITLE
make "omer" crate work without being part of the workspace 

### ISSUE THREAD

**Issue by omershlo** [kobigurk/librustzcash_omer#1]
Hi, 

What you did is added "omer" to the workspace. What I want to do is to consume the workspace from outside: 
```rust
[dependencies.sapling-crypto]
git = "https://github.com/zcash/librustzcash.git"
rev = "06da3b9ac8f278e5d4ae13088cf0a4c03d2c13f5"

[dependencies.pairing]
git = "https://github.com/zcash/librustzcash.git"

```

the reason is that I don't want to fork `librustzcash` because then if zcash will update the code I will not be able to update it without doing the fork again.

**Comment by kobigurk** [comment]
OK, I tried that as well :smiley: 
Check this out: https://github.com/kobigurk/librustzcash_omer_external

**Comment by kobigurk** [comment]
I suspect that it's probably in some other usage of it?

**Comment by kobigurk** [comment]
OK! I added "rev" as well for pairing and you didn't! That's the difference.

**Comment by omershlo** [comment]
holy crap! this is it!

**Comment by omershlo** [comment]
thanks!!!
